### ISSUE TITLE
发送命令后无响应

### ISSUE THREAD

**Issue by MareDevi** [nonebot/plugin-status#3]
安装成功并
按照文档配置
发送/状态 或者戳一戳之后均无反应
![6E133BE0-1F9F-4078-B909-6C15D20B9807](https://github.com/nonebot/plugin-status/assets/110676727/a0f4f63f-96f8-40fb-82cc-a12e293f122c)

**Comment by yanyongyu** [comment]
请提供你的运行日志，你是否配置了superuser？

**Comment by MareDevi** [comment]
啊，之前没有配置超级用户
现在正常了
感谢

**Comment by VincentZyu233** [comment]
> 请提供你的运行日志，你是否配置了superuser？

请问如何配置superuser？谢谢！

**Comment by yanyongyu** [comment]
> @VincentZyu233 请问如何配置superuser？谢谢！

https://nonebot.dev/docs/appendices/config#superusers
